# Generated by Django 5.2.3 on 2025-07-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bondup_core', '0004_rename_content_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
