# Generated by Django 5.2.3 on 2025-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondup_core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
    ]
