# Generated by Django 5.2.3 on 2025-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bondup_core', '0008_post_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
