# Generated by Django 5.2.3 on 2025-07-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bondup_core', '0009_rename_text_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
