# Generated by Django 5.2.3 on 2025-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondup_core', '0012_alter_profile_contact_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
